version: "2"

services:
  d-metron-api:
    container_name: "d-metron-api"
    image: d-metron-api
    build:
      context: .
      dockerfile: ./dockerfiles/app.docker.dev
    command: nodemon index.js
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
      - bridge-network
networks:
  default:
    driver: bridge
  bridge-network:
    external: true
